use rand::{Rng, rngs::ThreadRng};

fn main() {
    let mut output: String = "".to_owned();
    output.push_str(_title_page().as_str());
    output.push_str(_content(10).as_str());
    println!("{}", output.as_str());
}

fn _title_page() -> String {
    "\nOne Time Pad
Generated by pad-gen

This pad can be used to securely communicate with the owner of an identical pad.\n"
        .to_owned()
}

fn _content(num_pgs: usize) -> String {
    let mut rng = rand::rng();
    let mut output: String = "".to_owned();
    for pg_num in 1..(num_pgs + 1) {
        output.push_str(_header(pg_num, num_pgs).as_str());
        output.push_str(_pad(10, 10, &mut rng).as_str());
        output.push_str(_closer(pg_num, num_pgs).as_str());
    }
    output
}

fn _header(pg_num: usize, num_pgs: usize) -> String {
    format!("\nPage {} of {}\n", pg_num, num_pgs).to_owned()
}

fn _pad(l_length: usize, l_num: usize, rng: &mut ThreadRng) -> String {
    let mut output = "".to_owned();
    for l in 0..l_num {
        output.push_str(format!("{}\t", l).as_str());
        for _n in 0..l_length {
            //Capital letters are 65 to 90 in ASCII
            let c: char =
                char::from_u32((rng.next_u32() % 25) + 65).expect("Unable to convert u32 to char");
            output.push_str(format!("{} ", c).as_str());
        }
        output.push_str("\n");
    }
    output
}

fn _closer(pg_num: usize, num_pgs: usize) -> String {
    format!("Page {} of {}\n", pg_num, num_pgs).to_owned()
}
